baseURL = "https://kruemel.xyz/"
languageCode = "en-us"
title = "kruemel.xyz"
copyright = "© Krümel"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableEmoji = true

googleAnalytics = "G-5D76ZZD8WC"

[params]
	mode="toggle"
	useCDN=false
	dateFormat = "2006 Jan. 02."
	favicon = "/favicon.png"

# Social Tags
[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/kruemelxyz/"

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:kruemel.xyz@proton.me"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
